### PR TITLE
Created Dark Mode

### LINKED ISSUE #41: Night Mode UI
### **Feature request**:
I want to add night mode in the application using toggle switch

### **Is your feature request related to a problem? Please describe. (optional)**:
Helping to reduce eye strain

### **Describe the solution you'd like**:
 I would like to add the toggle switch so the user can switch from light to dark and vice versa

### **Describe alternatives you've considered**:
Rather than toggle switch we can also use toggle bar

### **Describe how this feature will be useful to our readers**:
Less eye strain at night

### PR DESCRIPTION
**Pull request by ManavArora26**
# Description

Added Dark theme to the website need to change the Layout according to the website a bit

Fixes # (issue no.)
Fixes #41 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Yes it works fine

- [ ] Test A
Button works just as fine 
- [ ] Test B
A little stuck at times but gets done as soon as possible

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Akshay6890** [comment]
> # Description
> Added Dark theme to the website need to change the Layout according to the website a bit
> 
> Fixes # (issue no.)
> Fixes #41
> 
> ## Type of change
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x ] New feature (non-breaking change which adds functionality)
> * [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> # How Has This Been Tested?
> Yes it works fine
> 
> * [ ]  Test A
>   Button works just as fine
> * [ ]  Test B
>   A little stuck at times but gets done as soon as possible
> 
> **Test Configuration**:
> 
> * Firmware version:
> * Hardware:
> * Toolchain:
> * SDK:
> 
> # Checklist:
> * [x ] My code follows the style guidelines of this project
> * [x ] I have performed a self-review of my own code
> * [ x] I have commented my code, particularly in hard-to-understand areas
> * [ x] I have made corresponding changes to the documentation
> * [x ] My changes generate no new warnings
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [x ] New and existing unit tests pass locally with my changes
> * [ x] Any dependent changes have been merged and published in downstream modules

Hey, can you add a video showcasing the work?

**Review by Akshay6890 — COMMENTED** [review]
Can I ask you a question? Why is a separate file created for Dark mode functionality?

**Comment by ManavArora26** [comment]
I created a separate file because I didn't knew exactly where the toggle switch will be the best , as usually I found it good to add in a toggle bar but we didn't had one in our website so i thought i will create a separate file so if it is okay wherever you will say i will just add the button right there

**Comment by Akshay6890** [comment]
> I created a separate file because I didn't knew exactly where the toggle switch will be the best , as usually I found it good to add in a toggle bar but we didn't had one in our website so i thought i will create a separate file so if it is okay wherever you will say i will just add the button right there

we do have a common header file, which is included in all pages! You can add the code to that! The file name is Header.html

**Comment by Akshay6890** [comment]
> I created a separate file because I didn't knew exactly where the toggle switch will be the best , as usually I found it good to add in a toggle bar but we didn't had one in our website so i thought i will create a separate file so if it is okay wherever you will say i will just add the button right there

check this file in the path bookstore/templates/client/header.html

**Comment by ManavArora26** [comment]
I will add it right there , sorry!!

**Comment by Akshay6890** [comment]
> I will add it right there , sorry!!

And make sure to include a video clip showcasing the work, make sure it works on all pages

**Comment by vikasdo** [comment]
@Akshay6890  is it valid. If  so we can merge it please check

**Comment by Akshay6890** [comment]
> @Akshay6890 is it valid. If so we can merge it please check

How is it valid? He created a new file for the toggle, the functionality will stay only on the page he created.

**Comment by Akshay6890** [comment]
> I will add it right there , sorry!!

you can also try to store the setting on a local session. this way the dark mode will stay even if we close or switch tabs.

**Comment by Akshay6890** [comment]
> I will add it right there , sorry!!

Below is my code Suggesstion:

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  padding: 25px;
  background-color: white;
  color: black;
  font-size: 25px;
}

.dark-mode {
  background-color: black;
  color: white;
}
</style>
</head>
<body>

<button id="dark-mode" onclick="myFunction()">Dark Mode</button>

<script>
function myFunction() {
   var button = document.getElementById("dark-mode");
   var element = document.body;
   if(button.innerHTML=="Dark Mode"){
   	element.classList.toggle("dark-mode");
    button.innerHTML="Light Mode";
   }
   else if(button.innerHTML=="Light Mode"){
    element.classList.toggle("dark-mode");
   	button.innerHTML="Dark Mode";
   }
}
</script>

</body>
</html>

**Comment by ManavArora26** [comment]
After i have done should i make a new pr request or we can add changes in this only?

**Comment by Akshay6890** [comment]
> After i have done should i make a new pr request or we can add changes in this only?
> 

you need to make new pull request

**Comment by ManavArora26** [comment]
Just made the changes and they were added here automatically!!

**Comment by Akshay6890** [comment]
> Just made the changes and they were added here automatically!!

ok

**Comment by Akshay6890** [comment]
> Just made the changes and they were added here automatically!!

can you add a video clip showcasing the work?

**Comment by ManavArora26** [comment]
I was trying to screen record but website is not displaying well in mine , I don't know why , it is coming like this, sometime it is coming like it should sometimes it is not 
error

**Comment by Akshay6890** [comment]
> I was trying to screen record but website is not displaying well in mine , I don't know why , it is coming like this, sometime it is coming like it should sometimes it is not 
> error
> 

you probably didnt close a tag properly.

**Comment by Akshay6890** [comment]
> I was trying to screen record but website is not displaying well in mine , I don't know why , it is coming like this, sometime it is coming like it should sometimes it is not 
> error
> 

you can add the style in head and the dark mode button after signup button! and after logiging in the dark theme button should be after logout.
and js goes below the body with "defer" as attribute to script tag

**Comment by ManavArora26** [comment]
Done!

**Comment by arpit456jain** [comment]
@Akshay6890 can i give it a try?

**Comment by Akshay6890** [comment]
> @Akshay6890 can i give it a try?

Do you want to work on it?

**Comment by arpit456jain** [comment]
> > @Akshay6890 can i give it a try?
> 
> Do you want to work on it?

What will be the level?

**Comment by Akshay6890** [comment]
> > > @Akshay6890 can i give it a try?
> > 
> > 
> > Do you want to work on it?
> 
> What will be the level?

i resolved them

**Comment by arpit456jain** [comment]
> > > > @Akshay6890 can i give it a try?
> > > 
> > > 
> > > Do you want to work on it?
> > 
> > 
> > What will be the level?
> 
> i resolved them

@Akshay6890 I am having a doubt that this dark mode features won't work properly because it lacks tha js code which is important 🤔

**Pull request closed without merging**
