### PR TITLE
Author Dashboard

### LINKED ISSUE #39: Make an author dashboard with separate dB for author
Make author dashboard so author can select their books and ratings

### PR DESCRIPTION
**Pull request by VishvamPorwal**
# Description

Added author Dashboard

For location I tried to create a user location heatmap

something like this....
heatmap
but i was unable to do it as it required use of some paid api's

Fixes #39  

Note:
Now there is one thing, before I added the automatic location feature, that format of location is not compatible with location metric data as it was kind of random and user dependant, so there might be an error if someone tries to rate the books from id's created before location feature.
But all the users registered after that automatic location are perfectly fine.

Ps: I am not very good at designing but I tried my best.

https://user-images.githubusercontent.com/59139142/114155580-46845880-993f-11eb-93d0-884659d4b086.mp4

### CODE REVIEW

**Comment by VishvamPorwal** [comment]
also sir label it GSSOC21 and level 3 same as the issue

**Comment by Akshay6890** [comment]
> also sir label it GSSOC21 and level 3 same as the issue

Hey, there are some merge conflicts, kindly review, as I am not able to see where the conflicts occured.

**Comment by VishvamPorwal** [comment]
> > also sir label it GSSOC21 and level 3 same as the issue
> 
> Hey, there are some merge conflicts, kindly review, as I am not able to see where the conflicts occured.

sure thing sir

**Comment by VishvamPorwal** [comment]
created #82

**Pull request closed without merging**
