### PR TITLE
Refractored Readme file

### PR DESCRIPTION
**Pull request by Aayush-hub**

### CODE REVIEW

**Comment by vikasdo** [comment]
Please update video link explaining steps and adding text
Link to Video :
https://drive.google.com/file/d/138YFG8sWrRJwtVqcWOFOt8Qin-ZQH7MX/view?usp=drivesdk

**Comment by Aayush-hub** [comment]
> Please update video link explaining steps and adding text
> Link to Video :
> https://drive.google.com/file/d/138YFG8sWrRJwtVqcWOFOt8Qin-ZQH7MX/view?usp=drivesdk

Now I need to do the changes?

**Comment by vikasdo** [comment]
No

**Comment by vikasdo** [comment]
Yes please add demo video link Readme

**Pull request merged**
