### PR TITLE
Contact Page Updated with Header

### LINKED ISSUE #53: Contact page missing
I want to add a contact page to the project with all details! Please assign me this with a **GSSOC** tag!

### PR DESCRIPTION
**Pull request by aishux**
# Description

I have fixed the contact page and the header is now visible! Along with the header the contact form data is even saved in the database and the code for sending mail notifications is also active! We only need to uncomment that code!

Fixes #53 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Form entries were saved in the database successfully.
- [x] Mails can be sent by uncommenting the code
- [x] Navbar works successfully 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

Book-ly

### CODE REVIEW

**Comment by Akshay6890** [comment]
> # Description
> I have fixed the contact page and the header is now visible! Along with the header the contact form data is even saved in the database and the code for sending mail notifications is also active! We only need to uncomment that code!
> 
> Fixes #53
> 
> ## Type of change
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  This change requires a documentation update
> 
> # How Has This Been Tested?
> * [x]  Form entries were saved in the database successfully.
> * [x]  Mails can be sent by uncommenting the code
> * [x]  Navbar works successfully
> 
> # Checklist:
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [x]  I have added tests that prove my fix is effective or that my feature works
> * [x]  New and existing unit tests pass locally with my changes
> * [x]  Any dependent changes have been merged and published in downstream modules
> 
> Book-ly

can you change the background color, or is the dark mode on?

**Comment by aishux** [comment]
No actually the theme is not common for any page right now, so I thought I will create a new issue for setting a proper theme for the entire site! If you want, I'll change the background color of this page and push back

**Comment by Akshay6890** [comment]
> No actually the theme is not common for any page right now, so I thought I will create a new issue for setting a proper theme for the entire site! If you want, I'll change the background color of this page and push back @Akshay6890

Change the theme similar to other pages such as login, signup page, this is to ensure consistency across the site for a good user experience. Hope you got it.

**Comment by aishux** [comment]
yes sir, will update and push back

**Comment by aishux** [comment]
updated the contact page theme according to other pages. @Akshay6890 
Screenshot 2021-03-30 at 1 29 40 PM

image

**Comment by vikasdo** [comment]
@Akshay6890  shall I merge this

**Comment by Akshay6890** [comment]
> @Akshay6890 shall I merge this

go ahead

**Pull request merged**
