### PR TITLE
Auto location feature

### LINKED ISSUE #52: Use of location api instead of manually letting users enter location.
### **Feature request**:

I am proposing to add an ip address based location api to store location data instead of letting users writing them by hand.

### **Is your feature request related to a problem?**:

When users are manually entering their info they are using their own way to describe it.
Hence it is hard to use it meaningfully and easily in various places like dashboards. 

### **Describe the solution you'd like**:

By using location api we can easily get location in a standard format that can then be later used more sensibly.

### **Describe alternatives you've considered**:
An alternative to this be we can use a datalist tag passing in every country and their cities to the html page.

### **Additional context:**
One thing I should mention is sometimes the location given by this api can be little inaccurate so its a risk but I think for better data format we should do it.

<hr/>

I would like to work on this feature if you think it will be useful.
Also label it GSSOC21.

### PR DESCRIPTION
**Pull request by VishvamPorwal**
# Description

used a free api to auto locate user when they register and store the same
format of location - city, Country, latitude, longitude

Fixes #52 

Note: As it is a free api there is a limit to number of calls per day

**Also Sir Please make sure to label my Pull request GSSOC21 and level 3 otherwise I wont receive any marks, also please label my previous pull requests the same as well as I have not received a single point up till now**

### CODE REVIEW

**Comment by vikasdo** [comment]
can you post an video  how it looks

**Comment by VishvamPorwal** [comment]
https://user-images.githubusercontent.com/59139142/113394605-28a27b00-93b6-11eb-8250-2bb35e41fed9.mp4

I know its a couple of km's off the exact position but at least it is standardised which is crucial.

**Comment by vikasdo** [comment]
Good work

**Comment by VishvamPorwal** [comment]
@vikasdo sir I didn't get any marks please label this pr GSSOC21 and level 3

**Pull request merged**
