### PR TITLE
Added auto labeler for issues

### LINKED ISSUE #54: Add github action to auto label issues
### **Feature request**:
Add github action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time to maintainer to add labels, I can add a script which can auto label issues with GSSOC21 label  whenever contributors asks to work under that label.

### PR DESCRIPTION
**Pull request by Aayush-hub**
# Description

Added github action to auto label issues with GSSOC21 label when contributor asks to work under gssoc21.

Fixes #54 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vikasdo** [comment]
What is level it assigns for issue

**Comment by vikasdo** [comment]
It will label it as GSSOC21 only I think

**Comment by Aayush-hub** [comment]
> It will label it as GSSOC21 only I think

Yes it will add GSSOC21 label only, if the contributor asks to work under it.

**Comment by Aayush-hub** [comment]
> What is level it assigns for issue

Levels are upto mentors, so we can't set a default level to auto add to a issue.

**Pull request merged**
