### PR TITLE
Made Contact us page more attractive

### LINKED ISSUE #75: [Gssoc'21] Making Contact us page more attractive
### **Feature request**:
I want to try to make contact page more attractive and cool

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description

I had make contact page more attractive and cool

Fixes #75 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
I will upload a sample video in comment
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114056831-b0edb800-98af-11eb-98e4-37906274879a.mp4

**Comment by arpit456jain** [comment]
@Akshay6890 kindly add labels of gssoc'21 and level 3 if possible

**Comment by arpit456jain** [comment]
@Akshay6890 why did you close the issue??😅

**Comment by arpit456jain** [comment]
@Akshay6890 just level 1😅 it takes more than 3 hours.
Ok no problem .

**Comment by Akshay6890** [comment]
> @Akshay6890 just level 1😅 it takes more than 3 hours.
> Ok no problem .

I appreciate the work you did, but we do have rules on how to give levels based on feature/ severity of bug. Hope you understand. There will no bias what so ever. 😊

**Pull request merged**
