### PR TITLE
added dark mode to admin dashboard

### LINKED ISSUE #125: Adding dark mode to Admin Dashboard
Adding dark mode to Admin Dashboard

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description

Adding dark mode to Admin Dashboard 

Fixes #125 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/119970437-562e2e00-bfcd-11eb-9f3e-009b51fc68ce.mp4

**Comment by arpit456jain** [comment]
@Akshay6890 i had added dark mode to admin dash board also .
If any page is left please let me know

**Comment by Akshay6890** [comment]
> @Akshay6890 i had added dark mode to admin dash board also .
> If any page is left please let me know

have you checked /dashboard?

**Comment by arpit456jain** [comment]
> > @Akshay6890 i had added dark mode to admin dash board also .
> > If any page is left please let me know
> 
> have you checked /dashboard?
Not yet..
I am adding dark mode to it..

But @Akshay6890 there is one problem in that page.
Thers is no navbar on top in that page...so i am adding toggle button in side navbar i hope its fine..

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/120060449-8b8e5680-c075-11eb-8b6f-9c3c3f30055f.mp4

**Comment by arpit456jain** [comment]
@Akshay6890 please review

**Comment by Akshay6890** [comment]
> > > @Akshay6890 i had added dark mode to admin dash board also .
> > > If any page is left please let me know
> > 
> > 
> > have you checked /dashboard?
> > Not yet..
> > I am adding dark mode to it..
> 
> But @Akshay6890 there is one problem in that page.
> Thers is no navbar on top in that page...so i am adding toggle button in side navbar i hope its fine..

possible to roll back changes? It doesn't look good. Only if it's not a burden,

**Comment by arpit456jain** [comment]
You mean removing dark mode from dashboard?

Or just removing the toggle button??

**Comment by arpit456jain** [comment]
@Akshay6890

**Pull request merged**
