### PR TITLE
change password feature

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description

Fixes # (issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
currently there is nothing in this PR .
I created this so that i can work on it tomorrow i will commit changes soon so please don't close it

**Comment by Akshay6890** [comment]
> currently there is nothing in this PR .
> I created this so that i can work on it tomorrow i will commit changes soon so please don't close it

Okay.

**Comment by arpit456jain** [comment]
@Akshay6890 i had implemented 
1. Change Password feature
2. show Password
3. sweet alert for logout

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/120337493-ff985b00-c310-11eb-9062-14312408c2cd.mp4

**Pull request merged**
