### PR TITLE
[Gssoc'21] fixed the bug in contact form and error/success message.

### LINKED ISSUE #67: [Gssoc'21] Bug in contact Us
### **Describe the bug:**
There is s bug in contact us page please watch this video.

https://user-images.githubusercontent.com/55352601/113180497-6b593b80-926e-11eb-86a7-0fc20f3d9f9b.mp4

As you can see any one can overload the server by clicking submitting repetitively.
Also there are no success/error messgage.
### **To Reproduce:**
4. See an error

### **Expected behavior:**
All the fields must be required with some validations

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description
There was a bug in contact us form

Fixes #67 

## Type of change
bug fix and added some validations to contact form 
please watch this video

https://user-images.githubusercontent.com/55352601/113417769-cc555080-93e1-11eb-9d3a-c428e6ab8fe7.mp4

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Akshay6890  I had fixed the bug in contact form as you can see in the above video.
I had added some validations in form.
Kindly review it and merge it so I can create a new issue as you told me

**Comment by arpit456jain** [comment]
@Akshay6890 There was also a bug in error success message the success message was not displaying on submit.

I had also fixed that issue. Kindly add labels of  gssoc'21 and if possible level3 as on issue you give me level2 but Its very challenging to find the bug in error/success message that why is was not displaying.

**Comment by vikasdo** [comment]
image
so why is white background there for email .please check

**Comment by arpit456jain** [comment]
> image
> so why is white background there for email .please check

Its because of by-default CSS of browser 
Untitled11

The bug in contact form was.

It can be submitted without entering anything
No validation's
NO Error success message visible.

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/113469799-27348980-946e-11eb-9060-788498b2a063.mp4

@vikasdo as you can also see in this video it is by default CSS for auto-selected input. I can't over write it .
It is looking weird because background of input is black.

If the background is white then it will not look so weird.
I can change the background from black to white but I can't over write the user agent CSS .

**Comment by vikasdo** [comment]
@VishvamPorwal  then keep it simple white backgroung with bordered .can you modify contact form

**Comment by VishvamPorwal** [comment]
> @VishvamPorwal then keep it simple white backgroung with bordered .can you modify contact form

Sir I think you meant to address @arpit456jain here.

**Comment by arpit456jain** [comment]
> @VishvamPorwal then keep it simple white backgroung with bordered .can you modify contact form

ok

**Comment by arpit456jain** [comment]
> @VishvamPorwal then keep it simple white backgroung with bordered .can you modify contact form

b1

is it ok ?

**Comment by Akshay6890** [comment]
> > @VishvamPorwal then keep it simple white backgroung with bordered .can you modify contact form
> 
> b1
> 
> is it ok @vikasdo ?

try to use the styling used in login/ signup page, for input fields

**Comment by arpit456jain** [comment]
> > > @VishvamPorwal then keep it simple white backgroung with bordered .can you modify contact form
> > 
> > 
> > b1
> > is it ok @vikasdo ?
> 
> try to use the styling used in login/ signup page, for input fields

@Akshay6890 don't mind but this issue was not for styling of contact form. If you want enhancement in contact form I will create a new issue for that and will improve the UI of contact page properly .
Before that I had to solve the issue #70 as you told me to do.

**Pull request merged**
