### PR TITLE
Gssoc'21 Fixes Bug in Login/Signup System and add form validations

### LINKED ISSUE #40: Gsoc'21 Bug in Login/Signup System
### **Describe the bug:**
There is a very crucial bug in login/Signup system because when i clicked on login without signing up even without entering anything , both field empty I got Login Successful which is very wrong It should give me a message to fill the fields 
I am attaching a video for better understanding my issue.

https://user-images.githubusercontent.com/55352601/111906637-71ce0300-8a77-11eb-841b-59f07141d8ae.mp4

### **To Reproduce:**
4. See an error

### **Expected behavior:**
It should give me required message to fill the fields correctly.
### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by arpit456jain**
problems
1.There was a very crucial bug in login/Signup system because when i clicked on login without signing up even without entering anything , both field empty I got Login Successful which is very wrong It should give me a message to fill the fields
which can be seen in this video.

https://user-images.githubusercontent.com/55352601/112198185-dbded780-8c32-11eb-9171-d813669d7662.mp4

2. The first error message of "Please login to access this page was not in red color!"
prob1

3 There was no form validations anyone can overload the server and database as mentioned above.

Fixes #40 
## Type of change
I had added Form Validations in both login and signup with proper error and success message and fixes all issues mentioned above.
 Please watch this video full for better understanding of my updated code.

https://user-images.githubusercontent.com/55352601/112198889-98389d80-8c33-11eb-8f16-a8dcbf32c0ff.mp4

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
I had attached a video above please look into it

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Akshay6890  sir please add the label of gssoc'21 as i am a gssoc'21 participant

**Comment by arpit456jain** [comment]
Thank god all checks passed , I was very stressed for a second.....sir please merge this PR before any other PR got merged and any conflicts occur otherwise i had to done the changes again which will be little bit difficult for me.
And please add labels of gssoc'21

**Comment by arpit456jain** [comment]
Sorry to disturb sir , but I didn't get any score for this. Can you please check it what went wrong.

**Comment by Akshay6890** [comment]
> Sorry to disturb sir , but I didn't get any score for this. Can you please check it what went wrong.

arpit create a new pull request

**Comment by arpit456jain** [comment]
ok sir

**Comment by arpit456jain** [comment]
sir should i create new issue first??

**Comment by Akshay6890** [comment]
> sir should I create a new issue first??

i already created one, just comment on the issue, I will assign you

**Comment by arpit456jain** [comment]
ok sir

**Pull request merged**
