### PR TITLE
Updated README.md with contributors section

### PR DESCRIPTION
**Pull request by rajeshpanjiyar**
# Description

Updated readme file with contributors section where the profile of contributors of this project would be visible.

Fixes # (32)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested in the comment section of Github as it is readme update Github comment section has preview button which shows the readme.md files or content.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rajeshpanjiyar** [comment]
I request you to label this PR with **gssoc21** and **Level**.

**Comment by rajeshpanjiyar** [comment]
I again request you to label this PR with **gssoc21** and **Level**.

**Comment by rajeshpanjiyar** [comment]
I request you change **level 1**  to **level1**. As level 1 is not valid already mentioned by GSSoC program manager.

**Comment by vikasdo** [comment]
Tell us whether you received points as I have updated now.please check and
let me know

**Comment by rajeshpanjiyar** [comment]
I haven't got point and i checked the level format. It should be capital L i.e **Level1**

**Pull request merged**
