### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by chazuttu**
Added a Toggle button #96

### CODE REVIEW

**Comment by Akshay6890** [comment]
> Added a Toggle button #96

hey, can you provide a video showcasing the work?

**Comment by chazuttu** [comment]
> > Added a Toggle button #96
> 
> hey, can you provide a video showcasing thdo it

**Comment by chazuttu** [comment]
@Akshay6890 Okk Sir , I will do it

**Comment by chazuttu** [comment]
@Akshay6890 I am tested covid positive for the 2nd time so I was not able to make a demo video. Thanks for merging my PR

**Comment by Akshay6890** [comment]
> @Akshay6890 Sir I am tested covid positive for the 2nd time so I was not able to make a demo video. Thanks for merging my PR

Hope you are doing good @chazuttu, don't worry about this, your health and safety is a high priority, wishing you a speedy recovery 😃

**Pull request merged**
